cluster:
  name: my-cluster

networkPolicies:
  enabled: true

upstream:
  cluster:
    name: my-cluster
  destinations:
    - name: loki
      type: loki
      url: http://logging-loki-write.logging.svc.cluster.local:3100/loki/api/v1/push
  alloy-logs:
    enabled: true
  podLogs:
    enabled: true
    destinations:
      - loki
    collector: alloy-logs
